### PR TITLE
Return subscription id from Meteor.subscribe

### PR DESCRIPTION
**Pull request by okland**
Return Meteor.subscription id from subscribe function so we could handle UnSubscribe

### CODE REVIEW

**Comment by thani-sh** [comment]
Hi @okland,
I'm extremely sorry for the delay. I'll merge this right now.

**Comment by okland** [comment]
:+1:

**Comment by arunoda** [comment]
@mnmtanish Did you publish this to NPM?

**Comment by arunoda** [comment]
Okay. Seems like it is. (v2.6.0).
Great.

**Pull request merged**
